# Generated by Django 4.0.4 on 2022-04-21 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_remove_teacher_user_remove_user_employment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='mood',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
