# Generated by Django 4.0.4 on 2022-04-21 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='user',
        ),
        migrations.RemoveField(
            model_name='user',
            name='employment',
        ),
        migrations.RemoveField(
            model_name='user',
            name='idproof',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_type',
        ),
        migrations.DeleteModel(
            name='Other',
        ),
        migrations.DeleteModel(
            name='Teacher',
        ),
    ]
